default:
  # timeout: 600 # timeout in minutes
  # except:
  #   - schedules
  cache:
    paths:
      - build/snapshot-*/*/*
      - build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      - build/snapshot-lean-$LEAN_VERSION/failure.toml
      # - ../build/snapshot-*/*/*/src
      # - ../build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      # - ../build/snapshot-lean-$LEAN_VERSION/failure.toml
  before_script:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - TAG=snapshot-`date -u "+%Y-%m"`
  - source ~/.elan/env
  - elan toolchain install leanprover-community/lean:nightly
  - elan toolchain install 3.4.2
  - elan toolchain install 3.4.1
  - elan toolchain install 3.4.0
  - elan default leanprover-community/lean:nightly # 3.4.2
  - lean -v
  - leanpkg build

stages:
  - mathlib
  - build

mathlib:
  except:
    - schedules
  variables:
    LEAN_VERSION: "3.4.2"
  stage: mathlib
  artifacts:
    paths:
      - build/snapshot-*/*/*
      - build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      - build/snapshot-lean-$LEAN_VERSION/failure.toml
      # - ../build/snapshot-*/*/*/src
      # - ../build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      # - ../build/snapshot-lean-$LEAN_VERSION/failure.toml
  script:
    - lean --run src/check.lean --makefile $LEAN_VERSION snapshot-lean-$LEAN_VERSION
    - cp scripts/detect_errors.py build/snapshot-lean-$LEAN_VERSION/
    - cd build/snapshot-lean-$LEAN_VERSION
    # - timeout 10200 make
    - timeout 10200 make | python detect_errors.py || true
    # - timeout 10200 lean --run src/check.lean snapshot-2019-10 --mathlib | python scripts/detect_errors.py

test:
  except:
    - schedules
  stage: build
  artifacts:
    paths:
      - build/snapshot-*/*/*
      - build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      - build/snapshot-lean-$LEAN_VERSION/failure.toml
      # - ../build/snapshot-*/*/*/src
      # - ../build/snapshot-lean-$LEAN_VERSION/snapshot.toml
      # - ../build/snapshot-lean-$LEAN_VERSION/failure.toml
  variables:
    LEAN_VERSION: "3.4.2"
  script:
    # - lean --run src/check.lean snapshot-2019-10
    - lean --run src/check.lean --makefile $LEAN_VERSION snapshot-lean-$LEAN_VERSION
    - cd build/snapshot-lean-$LEAN_VERSION
    - make || true
    - cd ../..
    - cp build/snapshot-lean-$LEAN_VERSION/snapshot.toml  build/snapshot-lean-$LEAN_VERSION/failure.toml snapshot/$LEAN_VERSION/
    - git clone --single-branch --branch snapshot https://$GITLAB_TOKEN@gitlab.com/simon.hudon/lean-depot snapshot || true
    - mkdir -p snapshot/3.4.2
    - mkdir -p snapshot/3.5.0
    - mkdir -p snapshot/lean-nightly
    - cd snapshot
    - git add $LEAN_VERSION/snapshot.toml $LEAN_VERSION/failure.toml
    - git commit -m "new" || true
    - git push origin snapshot || true

release:
  only:
    - schedules
  stage: build
  variables:
    LEAN_VERSION: "3.4.2"
  script:
    - git remote add release https://$GITLAB_TOKEN@gitlab.com/simon.hudon/lean-depot.git
    - git fetch --all
    - git checkout snapshot
    - cp $LEAN_VERSION/snapshot.toml $LEAN_VERSION/snapshot-$TAG.toml
    - git add $LEAN_VERSION/snapshot-$TAG.toml
    - git config --global user.email "machine@email.com"
    - git config --global user.name "machine"
    - git commit -m "new"
    - git fetch release --tags
    - git tag $TAG
    - git push release snapshot
    - git push release tag $TAG

bump:
  only:
    - schedules
  stage: build
  script:
    - git remote add release https://$GITLAB_TOKEN@gitlab.com/simon.hudon/lean-depot.git
    - git fetch
    - git checkout master
    - lean --run src/check.lean --update
    - git add pkgs/*.toml
    - git config --global user.email "machine@email.com"
    - git config --global user.name "machine"
    - git commit -m "new-snapshot" || true
    - git push release master || true
