cache:
  paths:
    - build/
test:
  stage: test
  script:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - elan toolchain install leanprover-community/lean:nightly
  - elan toolchain install 3.4.2
  - elan default leanprover-community/lean:nightly # 3.4.2
  - lean -v
  - leanpkg build
  - lean --run src/check.lean
