default:
  # timeout: 600 # timeout in minutes
  cache:
    paths:
      - .
  before_script:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - elan toolchain install leanprover-community/lean:nightly
  - elan toolchain install 3.4.2
  - elan toolchain install 3.4.1
  - elan toolchain install 3.4.0
  - elan default leanprover-community/lean:nightly # 3.4.2
  - lean -v
  - leanpkg build

mathlib:
  stage: mathlib
  artifacts:
    paths:
      - .
  script:
    - lean --run src/check.lean snapshot-2019-10 --mathlib

test:
  stage: build
  artifacts:
    paths:
      - .
  script:
    - lean --run src/check.lean snapshot-2019-10
