default:
  # timeout: 600 # timeout in minutes
  cache:
    paths:
      - build/snapshot-*/*/*/src
      - build/snapshot-lean-3.4.2--2019-10/snapshot.toml
      - build/snapshot-lean-3.4.2--2019-10/failure.toml
  before_script:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - elan toolchain install leanprover-community/lean:nightly
  - elan toolchain install 3.4.2
  - elan toolchain install 3.4.1
  - elan toolchain install 3.4.0
  - elan default leanprover-community/lean:nightly # 3.4.2
  - lean -v
  - leanpkg build

stages:
  - mathlib
  - build

mathlib:
  stage: mathlib
  artifacts:
    paths:
      - build/snapshot-*/*/*/src
      - build/snapshot-lean-3.4.2--2019-10/snapshot.toml
      - build/snapshot-lean-3.4.2--2019-10/failure.toml
  script:
    - lean --run src/check.lean
    - cd build/snapshot-lean-3.4.2--2019-10
    - timeout 10200 make | python scripts/detect_errors.py
    # - timeout 10200 lean --run src/check.lean snapshot-2019-10 --mathlib | python scripts/detect_errors.py

test:
  stage: build
  artifacts:
    paths:
      - build/snapshot-*/*/*/src
      - build/snapshot-lean-3.4.2--2019-10/snapshot.toml
      - build/snapshot-lean-3.4.2--2019-10/failure.toml
  script:
    # - lean --run src/check.lean snapshot-2019-10
    - lean --run src/check.lean
    - cd build/snapshot-lean-3.4.2--2019-10
    - make
