[package]
url = "https://github.com/leanprover-community/lean-perfectoid-spaces"
description = "Perfectoid spaces in the Lean formal theorem prover"
auto_update = true
commit = "14280435515dea23fc143f7dee4ff2e514233786"
