[package]
url = "https://github.com/leanprover-community/mathlib-nursery"
description = "missing"
auto_update = true
lean_support = ["3.4.2","3.5.0","nightly"]
commit = "0479b31fa5b4d39f41e89b8584c9f5bf5271e8ec"
