
[snapshot.mathlib]
git = ["https://github.com/leanprover-community/mathlib", "https://github.com/leanprover/mathlib"]
rev = "bf509d782bb6d7a1e0e62f8b88b136e2d671efba"
desc = "Lean mathematical components library"

